;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Phase.Day1.Day",DevComment="1일차 낮")
+GameplayTagList=(Tag="Phase.Day1.Night",DevComment="1일차 밤")
+GameplayTagList=(Tag="Phase.Day2.Day",DevComment="2일차 낮")
+GameplayTagList=(Tag="Phase.Day2.Night",DevComment="2일차 밤")
+GameplayTagList=(Tag="Phase.Day3.Day",DevComment="3일차 낮")
+GameplayTagList=(Tag="Phase.Day3.Night",DevComment="3일차 밤")
+GameplayTagList=(Tag="Phase.Day4.Day",DevComment="4일차 낮")
+GameplayTagList=(Tag="Phase.Day4.Night",DevComment="4일차 밤")
+GameplayTagList=(Tag="Ability",DevComment="")
+GameplayTagList=(Tag="Ability.Monster",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.Attack",DevComment="")

